### ISSUE TITLE
Projecting real images into the latent space

### ISSUE THREAD

**Issue by gabemarx** [LynnHo/EigenGAN-Tensorflow#2]
Hello!

I was wondering if there is a planned functionality to get the latent variables (U,L,z etc)  of a real image that is similar to the dataset the GAN was trained on, essentially a way to recreate the metrics in Table 1 of the publication...

**Comment by LynnHo** [comment]
@gabemarx There is no plan now. I think the current architecture is not powerful enough, so it's hard to learn a good inversion. I think cooperating with StyleGAN architecture should be better, we will try in the future.
