### ISSUE TITLE
网络如何学习到权重较大的特征向量呢？

### ISSUE THREAD

**Issue by dingyitk159** [LynnHo/EigenGAN-Tensorflow#6]
网络中似乎没有对L的大小作约束，只对U的正交性做了约束，它是怎么保证像PCA一样能够找到每一层的主成分呢？

**Comment by LynnHo** [comment]
> 网络中似乎没有对L的大小作约束，只对U的正交性做了约束，它是怎么保证像PCA一样能够找到每一层的主成分呢？

线性情况有理论证明（见附录），而非线性情况目前没有理论保证，但实验现象表明确实能够在不同层找到一些可解释的维度。

**Comment by dingyitk159** [comment]
非常感谢您的回答，很棒的工作！
