### ISSUE TITLE
maximum of n_traversal?

### ISSUE THREAD

**Issue by Shelomith** [LynnHo/EigenGAN-Tensorflow#7]
Hi, Thanks for your great work!

I'd like to know What is the Maximum value of parameter 'n_traversal'  when I test on Celeb-A dataset generator?

**Comment by LynnHo** [comment]
@Shelomith `n_traversal` different persons/identities will be produced.

**Comment by Shelomith** [comment]
Yep, the Celeb-A dataset (used for training) contains 10K identities. 
Does it mean that, if I change the n_traversal value, the generator can produce more than 10K different fake identities?

**Comment by LynnHo** [comment]
@Shelomith An ideal generator should be able to produce infinite identities. However, limited to the finite data, we don't know the maximum number of identities a generator can produce. It is a novel question.

From my perspective, the generator can produce more than 10K identities for CelebA; but it should be carefully verified.
